# Generated by Django 5.2.15 on 2026-07-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optinsubscriber',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16, unique=True),
        ),
    ]
